ame: Build and Push Docker Image

on:
  push:
    branches:
      - main

env:
  DOCKER_USERNAME: ${{ hamed21 }}
  DOCKER_PASSWORD: ${{ Hamed@12345 }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ hamed21 }}
          password: ${{Hamed@12345 }}
      - name: Build Docker image
        run: |
          docker build -t myapp:latest .
      - name: Push Docker image
        run: |
          docker tag myapp:latest ${{ hamed21 }}/myapp:latest
          docker push ${{ Hamed@12345 }}/myapp:latest
